version: "3.7"
services:
  node_app:
    build:
      context: .
    command: ["npm", "start"]
    ports:
      - "80:80"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

